import { DynamicFieldDef, StudentData, StaffData } from '../types';

export const DYNAMIC_STUDENT_FIELDS: DynamicFieldDef[] = [
  // Primary Identity
  {
    key: 'student.full_name',
    label: 'Full Name',
    category: 'identity',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 360,
    defaultHeight: 38,
    placeholder: 'Jean Niyonkuru',
    iconName: 'User',
    defaultStyle: {
      fontSize: 20,
      fontWeight: 700,
      color: '#0f172a',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'student.first_name',
    label: 'First Name',
    category: 'identity',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 200,
    defaultHeight: 32,
    placeholder: 'Jean',
    iconName: 'UserCheck',
    defaultStyle: {
      fontSize: 16,
      fontWeight: 600,
      color: '#1e293b',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'student.last_name',
    label: 'Last Name',
    category: 'identity',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 200,
    defaultHeight: 32,
    placeholder: 'Niyonkuru',
    iconName: 'UserCheck',
    defaultStyle: {
      fontSize: 16,
      fontWeight: 600,
      color: '#1e293b',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'student.middle_name',
    label: 'Middle Name',
    category: 'identity',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 180,
    defaultHeight: 30,
    placeholder: 'Pierre',
    iconName: 'User',
    defaultStyle: {
      fontSize: 15,
      fontWeight: 500,
      color: '#334155',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'student.student_number',
    label: 'Student Number',
    category: 'identity',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 220,
    defaultHeight: 32,
    placeholder: 'STU-2026-001',
    iconName: 'Hash',
    defaultStyle: {
      fontSize: 15,
      fontWeight: 700,
      color: '#0369a1',
      fontFamily: 'monospace',
      letterSpacing: 1,
    },
  },
  {
    key: 'student.photo_url',
    label: 'Student Photo',
    category: 'identity',
    cardType: 'student',
    defaultType: 'image',
    defaultWidth: 160,
    defaultHeight: 200,
    placeholder: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    iconName: 'Camera',
    defaultStyle: {
      borderRadius: 10,
      borderColor: '#0284c7',
      borderWidth: 2,
      objectFit: 'cover',
    },
  },
  // Academic
  {
    key: 'student.class_id',
    label: 'Class / Grade',
    category: 'academic',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 180,
    defaultHeight: 30,
    placeholder: 'Grade 10 - Section A',
    iconName: 'GraduationCap',
    defaultStyle: {
      fontSize: 15,
      fontWeight: 600,
      color: '#0f172a',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'student.gender',
    label: 'Gender',
    category: 'personal',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 140,
    defaultHeight: 28,
    placeholder: 'Male (M)',
    iconName: 'Smile',
    defaultStyle: {
      fontSize: 14,
      fontWeight: 500,
      color: '#475569',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'student.birth_date',
    label: 'Birth Date',
    category: 'personal',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 180,
    defaultHeight: 28,
    placeholder: '14 May 2012',
    iconName: 'Calendar',
    defaultStyle: {
      fontSize: 14,
      fontWeight: 500,
      color: '#475569',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'student.birth_place',
    label: 'Birth Place',
    category: 'personal',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 180,
    defaultHeight: 28,
    placeholder: 'Bujumbura',
    iconName: 'MapPin',
    defaultStyle: {
      fontSize: 14,
      fontWeight: 500,
      color: '#475569',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'student.address',
    label: 'Address',
    category: 'personal',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 260,
    defaultHeight: 32,
    placeholder: 'Rohero, Bujumbura',
    iconName: 'Home',
    defaultStyle: {
      fontSize: 13,
      fontWeight: 400,
      color: '#64748b',
      fontFamily: 'Inter',
    },
  },
  // Guardian / Emergency Contact
  {
    key: 'student.guardian_name',
    label: 'Guardian Name',
    category: 'contact',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 240,
    defaultHeight: 30,
    placeholder: 'Paul Niyonkuru',
    iconName: 'Shield',
    defaultStyle: {
      fontSize: 14,
      fontWeight: 500,
      color: '#334155',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'student.guardian_phone',
    label: 'Guardian Phone',
    category: 'contact',
    cardType: 'student',
    defaultType: 'text',
    defaultWidth: 200,
    defaultHeight: 30,
    placeholder: '+257 79 000 000',
    iconName: 'Phone',
    defaultStyle: {
      fontSize: 14,
      fontWeight: 600,
      color: '#0f172a',
      fontFamily: 'monospace',
    },
  },
];

export const DYNAMIC_STAFF_FIELDS: DynamicFieldDef[] = [
  // Primary Identity
  {
    key: 'staff.full_name',
    label: 'Full Name',
    category: 'identity',
    cardType: 'staff',
    defaultType: 'text',
    defaultWidth: 360,
    defaultHeight: 38,
    placeholder: 'Marie Ndayizeye',
    iconName: 'User',
    defaultStyle: {
      fontSize: 20,
      fontWeight: 700,
      color: '#0f172a',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'staff.first_name',
    label: 'First Name',
    category: 'identity',
    cardType: 'staff',
    defaultType: 'text',
    defaultWidth: 200,
    defaultHeight: 32,
    placeholder: 'Marie',
    iconName: 'UserCheck',
    defaultStyle: {
      fontSize: 16,
      fontWeight: 600,
      color: '#1e293b',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'staff.last_name',
    label: 'Last Name',
    category: 'identity',
    cardType: 'staff',
    defaultType: 'text',
    defaultWidth: 200,
    defaultHeight: 32,
    placeholder: 'Ndayizeye',
    iconName: 'UserCheck',
    defaultStyle: {
      fontSize: 16,
      fontWeight: 600,
      color: '#1e293b',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'staff.middle_name',
    label: 'Middle Name',
    category: 'identity',
    cardType: 'staff',
    defaultType: 'text',
    defaultWidth: 180,
    defaultHeight: 30,
    placeholder: '',
    iconName: 'User',
    defaultStyle: {
      fontSize: 15,
      fontWeight: 500,
      color: '#334155',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'staff.function',
    label: 'Function / Role',
    category: 'staff_info',
    cardType: 'staff',
    defaultType: 'text',
    defaultWidth: 280,
    defaultHeight: 32,
    placeholder: 'Mathematics Teacher',
    iconName: 'Briefcase',
    defaultStyle: {
      fontSize: 16,
      fontWeight: 600,
      color: '#0284c7',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'staff.photo_url',
    label: 'Staff Photo',
    category: 'identity',
    cardType: 'staff',
    defaultType: 'image',
    defaultWidth: 160,
    defaultHeight: 200,
    placeholder: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    iconName: 'Camera',
    defaultStyle: {
      borderRadius: 10,
      borderColor: '#0369a1',
      borderWidth: 2,
      objectFit: 'cover',
    },
  },
  {
    key: 'staff.phone',
    label: 'Phone Number',
    category: 'contact',
    cardType: 'staff',
    defaultType: 'text',
    defaultWidth: 200,
    defaultHeight: 30,
    placeholder: '+257 79 111 111',
    iconName: 'Phone',
    defaultStyle: {
      fontSize: 14,
      fontWeight: 600,
      color: '#0f172a',
      fontFamily: 'monospace',
    },
  },
  {
    key: 'staff.gender',
    label: 'Gender',
    category: 'personal',
    cardType: 'staff',
    defaultType: 'text',
    defaultWidth: 140,
    defaultHeight: 28,
    placeholder: 'Female (F)',
    iconName: 'Smile',
    defaultStyle: {
      fontSize: 14,
      fontWeight: 500,
      color: '#475569',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'staff.marital_status',
    label: 'Marital Status',
    category: 'personal',
    cardType: 'staff',
    defaultType: 'text',
    defaultWidth: 160,
    defaultHeight: 28,
    placeholder: 'Married',
    iconName: 'Heart',
    defaultStyle: {
      fontSize: 14,
      fontWeight: 500,
      color: '#475569',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'staff.number_of_children',
    label: 'Number of Children',
    category: 'personal',
    cardType: 'staff',
    defaultType: 'text',
    defaultWidth: 160,
    defaultHeight: 28,
    placeholder: '2',
    iconName: 'Users',
    defaultStyle: {
      fontSize: 14,
      fontWeight: 500,
      color: '#475569',
      fontFamily: 'Inter',
    },
  },
  {
    key: 'staff.address',
    label: 'Address',
    category: 'personal',
    cardType: 'staff',
    defaultType: 'text',
    defaultWidth: 260,
    defaultHeight: 30,
    placeholder: 'Bujumbura',
    iconName: 'Home',
    defaultStyle: {
      fontSize: 13,
      fontWeight: 400,
      color: '#64748b',
      fontFamily: 'Inter',
    },
  },
];

// Exact mock preview data matching requirements
export const PREVIEW_STUDENT_DATA: StudentData = {
  id: 101,
  school_id: 1,
  class_id: '10-A',
  first_name: 'Jean',
  last_name: 'Niyonkuru',
  middle_name: 'Pierre',
  gender: 'M',
  birth_date: '2012-05-14',
  birth_place: 'Bujumbura',
  address: 'Bujumbura',
  guardian_name: 'Paul Niyonkuru',
  guardian_phone: '+257 79 000 000',
  student_number: 'STU-2026-001',
  photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
  class_name: 'Grade 10 - Section A',
  academic_year: '2025 - 2026',
  school_name: 'Lycée International de Bujumbura',
};

export const PREVIEW_STAFF_DATA: StaffData = {
  id: 202,
  school_id: 1,
  first_name: 'Marie',
  last_name: 'Ndayizeye',
  middle_name: '',
  gender: 'F',
  marital_status: 'married',
  number_of_children: 2,
  function: 'Mathematics Teacher',
  phone: '+257 79 111 111',
  address: 'Bujumbura',
  photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
  department: 'Faculty of Science',
  employee_id: 'EMP-STAFF-042',
  school_name: 'Lycée International de Bujumbura',
};

export const ALTERNATIVE_STUDENT_PROFILES: StudentData[] = [
  PREVIEW_STUDENT_DATA,
  {
    id: 102,
    school_id: 1,
    class_id: '11-B',
    first_name: 'Amina',
    last_name: 'Hakizimana',
    middle_name: 'Grace',
    gender: 'F',
    birth_date: '2011-09-22',
    birth_place: 'Gitega',
    address: 'Kigobe, Bujumbura',
    guardian_name: 'Eric Hakizimana',
    guardian_phone: '+257 71 888 999',
    student_number: 'STU-2026-088',
    photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    class_name: 'Grade 11 - Science',
    academic_year: '2025 - 2026',
    school_name: 'Lycée International de Bujumbura',
  },
  {
    id: 103,
    school_id: 1,
    class_id: '12-A',
    first_name: 'David',
    last_name: 'Mugisha',
    middle_name: 'K.',
    gender: 'M',
    birth_date: '2010-02-18',
    birth_place: 'Ngozi',
    address: 'Kinindo, Bujumbura',
    guardian_name: 'Chantal Mugisha',
    guardian_phone: '+257 76 555 444',
    student_number: 'STU-2026-104',
    photo_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
    class_name: 'Grade 12 - Arts',
    academic_year: '2025 - 2026',
    school_name: 'Lycée International de Bujumbura',
  }
];

export const ALTERNATIVE_STAFF_PROFILES: StaffData[] = [
  PREVIEW_STAFF_DATA,
  {
    id: 203,
    school_id: 1,
    first_name: 'Dr. Joseph',
    last_name: 'Ndikumana',
    middle_name: 'Alain',
    gender: 'M',
    marital_status: 'married',
    number_of_children: 3,
    function: 'Principal / Headmaster',
    phone: '+257 79 333 222',
    address: 'Mutanga, Bujumbura',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    department: 'School Administration',
    employee_id: 'ADM-001',
    school_name: 'Lycée International de Bujumbura',
  },
  {
    id: 204,
    school_id: 1,
    first_name: 'Sarah',
    last_name: 'Uwimana',
    middle_name: 'Bella',
    gender: 'F',
    marital_status: 'single',
    number_of_children: 0,
    function: 'Head Librarian & Archivist',
    phone: '+257 77 444 888',
    address: 'Kiriri, Bujumbura',
    photo_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400',
    department: 'Academic Support',
    employee_id: 'LIB-012',
    school_name: 'Lycée International de Bujumbura',
  }
];
