import { CardTemplate, DimensionPreset } from '../types';

export const DIMENSION_PRESETS: DimensionPreset[] = [
  {
    id: 'cr80_landscape',
    name: 'CR80 Landscape (Standard ID)',
    width: 856,
    height: 540,
    description: 'Standard PVC ID card (85.6mm × 54mm)',
  },
  {
    id: 'cr80_portrait',
    name: 'CR80 Portrait (Vertical ID)',
    width: 540,
    height: 856,
    description: 'Vertical Lanyard Badge (54mm × 85.6mm)',
  },
  {
    id: 'badge_event',
    name: 'Conference Badge',
    width: 750,
    height: 500,
    description: 'Event / Visitor Pass (75mm × 50mm)',
  },
  {
    id: 'square_tag',
    name: 'Square NFC Tag',
    width: 600,
    height: 600,
    description: 'Square Access Token (60mm × 60mm)',
  },
];

export const INITIAL_STUDENT_TEMPLATE: CardTemplate = {
  version: 1,
  type: 'student',
  name: 'Standard Student ID Card',
  width: 856,
  height: 540,
  unit: 'px',
  orientation: 'landscape',
  background: {
    type: 'color',
    value: '#f8fafc',
  },
  elements: [
    // Top Brand Header Banner
    {
      id: 'elem_header_bg',
      name: 'Header Banner',
      type: 'rect',
      x: 0,
      y: 0,
      width: 856,
      height: 105,
      rotation: 0,
      zIndex: 1,
      locked: false,
      hidden: false,
      style: {
        backgroundColor: '#0369a1',
        borderRadius: 0,
      },
    },
    // Accent Stripe
    {
      id: 'elem_accent_stripe',
      name: 'Gold Accent Stripe',
      type: 'rect',
      x: 0,
      y: 105,
      width: 856,
      height: 8,
      rotation: 0,
      zIndex: 2,
      locked: false,
      hidden: false,
      style: {
        backgroundColor: '#f59e0b',
        borderRadius: 0,
      },
    },
    // School Logo Placeholder
    {
      id: 'elem_school_logo',
      name: 'School Logo',
      type: 'image',
      content: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&q=80&w=200',
      x: 28,
      y: 16,
      width: 72,
      height: 72,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        borderRadius: 36,
        borderColor: '#ffffff',
        borderWidth: 2,
        backgroundColor: '#ffffff',
        objectFit: 'contain',
      },
    },
    // School Title
    {
      id: 'elem_school_name',
      name: 'School Name',
      type: 'text',
      content: 'LYCÉE INTERNATIONAL DE BUJUMBURA',
      x: 115,
      y: 22,
      width: 580,
      height: 32,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 20,
        fontWeight: 800,
        color: '#ffffff',
        letterSpacing: 1.5,
        textTransform: 'uppercase',
      },
    },
    // School Motto / Subtitle
    {
      id: 'elem_card_subtitle',
      name: 'Card Title',
      type: 'text',
      content: 'STUDENT IDENTITY CARD • CARTE D\'ÉTUDIANT',
      x: 115,
      y: 58,
      width: 500,
      height: 24,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 600,
        color: '#bae6fd',
        letterSpacing: 2,
        textTransform: 'uppercase',
      },
    },
    // Academic Year Tag
    {
      id: 'elem_academic_year',
      name: 'Academic Year Badge',
      type: 'text',
      content: '2025 - 2026',
      x: 710,
      y: 24,
      width: 120,
      height: 30,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 13,
        fontWeight: 700,
        color: '#ffffff',
        backgroundColor: '#0284c7',
        borderRadius: 6,
        textAlign: 'center',
        lineHeight: 1.6,
      },
    },
    // Student Photo
    {
      id: 'elem_student_photo',
      name: 'Student Photo',
      type: 'image',
      field: 'student.photo_url',
      x: 35,
      y: 145,
      width: 190,
      height: 240,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        borderRadius: 12,
        borderColor: '#0284c7',
        borderWidth: 3,
        objectFit: 'cover',
        boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
      },
    },
    // Student Full Name
    {
      id: 'elem_student_name',
      name: 'Student Full Name',
      type: 'text',
      field: 'student.full_name',
      content: 'Student Full Name',
      x: 255,
      y: 145,
      width: 440,
      height: 38,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 24,
        fontWeight: 800,
        color: '#0f172a',
        textAlign: 'left',
      },
    },
    // Student ID / Matricule
    {
      id: 'elem_student_id_label',
      name: 'ID Label',
      type: 'text',
      content: 'STUDENT NUMBER / MATRICULE',
      x: 255,
      y: 190,
      width: 220,
      height: 18,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 700,
        color: '#64748b',
        letterSpacing: 1,
        textTransform: 'uppercase',
      },
    },
    {
      id: 'elem_student_id_value',
      name: 'Student Number',
      type: 'text',
      field: 'student.student_number',
      content: 'STU-2026-001',
      x: 255,
      y: 210,
      width: 240,
      height: 28,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'monospace',
        fontSize: 16,
        fontWeight: 700,
        color: '#0369a1',
      },
    },
    // Class / Grade
    {
      id: 'elem_class_label',
      name: 'Class Label',
      type: 'text',
      content: 'CLASS / SECTION',
      x: 510,
      y: 190,
      width: 180,
      height: 18,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 700,
        color: '#64748b',
        letterSpacing: 1,
        textTransform: 'uppercase',
      },
    },
    {
      id: 'elem_class_value',
      name: 'Class',
      type: 'text',
      field: 'student.class_id',
      content: 'Grade 10 - Section A',
      x: 510,
      y: 210,
      width: 200,
      height: 28,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: 600,
        color: '#0f172a',
      },
    },
    // Birth Date & Place
    {
      id: 'elem_dob_label',
      name: 'Birth Date Label',
      type: 'text',
      content: 'DATE OF BIRTH',
      x: 255,
      y: 248,
      width: 180,
      height: 18,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 700,
        color: '#64748b',
        letterSpacing: 1,
      },
    },
    {
      id: 'elem_dob_value',
      name: 'Birth Date',
      type: 'text',
      field: 'student.birth_date',
      content: '14 May 2012',
      x: 255,
      y: 268,
      width: 180,
      height: 26,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 500,
        color: '#1e293b',
      },
    },
    // Gender
    {
      id: 'elem_gender_label',
      name: 'Gender Label',
      type: 'text',
      content: 'GENDER',
      x: 450,
      y: 248,
      width: 100,
      height: 18,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 700,
        color: '#64748b',
        letterSpacing: 1,
      },
    },
    {
      id: 'elem_gender_value',
      name: 'Gender',
      type: 'text',
      field: 'student.gender',
      content: 'M',
      x: 450,
      y: 268,
      width: 80,
      height: 26,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 600,
        color: '#1e293b',
      },
    },
    // Guardian Contact
    {
      id: 'elem_guardian_label',
      name: 'Emergency Contact Label',
      type: 'text',
      content: 'GUARDIAN & EMERGENCY PHONE',
      x: 255,
      y: 305,
      width: 260,
      height: 18,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 700,
        color: '#64748b',
        letterSpacing: 1,
      },
    },
    {
      id: 'elem_guardian_value',
      name: 'Guardian Phone',
      type: 'text',
      field: 'student.guardian_phone',
      content: '+257 79 000 000',
      x: 255,
      y: 325,
      width: 240,
      height: 26,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'monospace',
        fontSize: 13,
        fontWeight: 600,
        color: '#0f172a',
      },
    },
    // QR Code in bottom-right corner
    {
      id: 'elem_qr_code',
      name: 'Verification QR',
      type: 'qr',
      field: 'student.student_number',
      content: 'STU-2026-001',
      x: 715,
      y: 145,
      width: 105,
      height: 105,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
        borderWidth: 1,
        borderRadius: 8,
      },
    },
    // Bottom Barcode Card Footer
    {
      id: 'elem_bottom_barcode',
      name: 'Access Barcode',
      type: 'barcode',
      field: 'student.student_number',
      content: 'STU-2026-001',
      x: 255,
      y: 410,
      width: 320,
      height: 75,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        barcodeShowText: true,
        color: '#000000',
      },
    },
    // Official Signature
    {
      id: 'elem_signature_img',
      name: 'Principal Signature',
      type: 'image',
      content: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=200',
      x: 670,
      y: 405,
      width: 130,
      height: 50,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        objectFit: 'contain',
        opacity: 0.85,
      },
    },
    {
      id: 'elem_signature_label',
      name: 'Signature Label',
      type: 'text',
      content: 'Principal Signature & Stamp',
      x: 650,
      y: 458,
      width: 170,
      height: 20,
      rotation: 0,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 600,
        color: '#94a3b8',
        textAlign: 'center',
      },
    },
  ],
};

export const INITIAL_STAFF_TEMPLATE: CardTemplate = {
  version: 1,
  type: 'staff',
  name: 'Official Staff Identity Pass',
  width: 856,
  height: 540,
  unit: 'px',
  orientation: 'landscape',
  background: {
    type: 'color',
    value: '#ffffff',
  },
  elements: [
    // Left Accent Sidebar
    {
      id: 'elem_staff_sidebar',
      name: 'Navy Left Column',
      type: 'rect',
      x: 0,
      y: 0,
      width: 250,
      height: 540,
      rotation: 0,
      zIndex: 1,
      locked: false,
      hidden: false,
      style: {
        backgroundColor: '#0f172a',
      },
    },
    // Staff Photo
    {
      id: 'elem_staff_photo',
      name: 'Staff Photo',
      type: 'image',
      field: 'staff.photo_url',
      x: 35,
      y: 40,
      width: 180,
      height: 220,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        borderRadius: 12,
        borderColor: '#38bdf8',
        borderWidth: 3,
        objectFit: 'cover',
      },
    },
    // Staff Employee ID badge in sidebar
    {
      id: 'elem_staff_empid_label',
      name: 'Employee ID Label',
      type: 'text',
      content: 'STAFF ID',
      x: 35,
      y: 280,
      width: 180,
      height: 18,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 11,
        fontWeight: 700,
        color: '#94a3b8',
        textAlign: 'center',
        letterSpacing: 2,
      },
    },
    {
      id: 'elem_staff_empid_val',
      name: 'Staff Phone',
      type: 'text',
      field: 'staff.phone',
      content: '+257 79 111 111',
      x: 35,
      y: 305,
      width: 180,
      height: 24,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'monospace',
        fontSize: 13,
        fontWeight: 600,
        color: '#38bdf8',
        textAlign: 'center',
      },
    },
    // QR Code on Left Column
    {
      id: 'elem_staff_qr',
      name: 'Access QR',
      type: 'qr',
      field: 'staff.phone',
      content: '+257 79 111 111',
      x: 65,
      y: 360,
      width: 120,
      height: 120,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        backgroundColor: '#ffffff',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#38bdf8',
      },
    },
    // Top Right School Banner
    {
      id: 'elem_staff_school_name',
      name: 'School Header',
      type: 'text',
      content: 'LYCÉE INTERNATIONAL DE BUJUMBURA',
      x: 290,
      y: 40,
      width: 520,
      height: 28,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: 800,
        color: '#0f172a',
        letterSpacing: 1,
      },
    },
    // Tag Badge
    {
      id: 'elem_staff_badge_type',
      name: 'Card Type Badge',
      type: 'text',
      content: 'OFFICIAL FACULTY & STAFF CARD',
      x: 290,
      y: 75,
      width: 280,
      height: 24,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 11,
        fontWeight: 700,
        color: '#0284c7',
        letterSpacing: 1.5,
      },
    },
    // Divider Line
    {
      id: 'elem_staff_divider',
      name: 'Divider Line',
      type: 'line',
      x: 290,
      y: 115,
      width: 520,
      height: 2,
      rotation: 0,
      zIndex: 2,
      locked: false,
      hidden: false,
      style: {
        backgroundColor: '#e2e8f0',
      },
    },
    // Staff Full Name
    {
      id: 'elem_staff_fullname',
      name: 'Staff Full Name',
      type: 'text',
      field: 'staff.full_name',
      content: 'Marie Ndayizeye',
      x: 290,
      y: 140,
      width: 520,
      height: 42,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 26,
        fontWeight: 800,
        color: '#0f172a',
      },
    },
    // Function / Role
    {
      id: 'elem_staff_func_label',
      name: 'Function Label',
      type: 'text',
      content: 'ROLE / FUNCTION',
      x: 290,
      y: 195,
      width: 200,
      height: 18,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 700,
        color: '#64748b',
        letterSpacing: 1,
      },
    },
    {
      id: 'elem_staff_func_val',
      name: 'Staff Function',
      type: 'text',
      field: 'staff.function',
      content: 'Mathematics Teacher',
      x: 290,
      y: 218,
      width: 320,
      height: 32,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: 700,
        color: '#0284c7',
      },
    },
    // Address / Location
    {
      id: 'elem_staff_addr_label',
      name: 'Address Label',
      type: 'text',
      content: 'OFFICE / RESIDENCE',
      x: 290,
      y: 265,
      width: 200,
      height: 18,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 700,
        color: '#64748b',
        letterSpacing: 1,
      },
    },
    {
      id: 'elem_staff_addr_val',
      name: 'Staff Address',
      type: 'text',
      field: 'staff.address',
      content: 'Bujumbura',
      x: 290,
      y: 285,
      width: 260,
      height: 26,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 500,
        color: '#334155',
      },
    },
    // Barcode Bottom
    {
      id: 'elem_staff_barcode',
      name: 'Staff Barcode',
      type: 'barcode',
      field: 'staff.phone',
      content: '+257 79 111 111',
      x: 290,
      y: 390,
      width: 340,
      height: 80,
      rotation: 0,
      zIndex: 3,
      locked: false,
      hidden: false,
      style: {
        barcodeShowText: true,
      },
    },
    // School Stamp
    {
      id: 'elem_staff_stamp',
      name: 'Official Stamp',
      type: 'image',
      content: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&q=80&w=200',
      x: 690,
      y: 375,
      width: 100,
      height: 100,
      rotation: 12,
      zIndex: 4,
      locked: false,
      hidden: false,
      style: {
        objectFit: 'contain',
        opacity: 0.75,
      },
    },
  ],
};
